CLIMATE_CHANGE_1 = ["Emissions",
"Net Zero",
"1.5 Degrees",
"Tipping Points",
"Adaptation",
"Migration"]

CLIMATE_CHANGE_2 = ["El Nino"]

CLEAN_ENERGY_1 = ["Renewable Energy",
"Solar Power",
"Wind Power",
"Hydro Power",
"Tidal Power",
"Geothermal Energy",
"Hydrogen",
"Biomass"]

CLEAN_ENERGY_2 = ["Batteries",
"Grids",
"Heat Pumps",
"Solar Panel Recycling",
"Hydro Grids"]

FOSSIL_FUELS_1 = ["Coal",
"Oil",
"Natural Gas/LNG",
"Nuclear",
"Carbon Dioxide",
"Methane"]

FOSSIL_FUELS_2 = ["Flaring",
"Fracking",
"Oil Sands",
"Willow Project Alaska",
"Carbon Capture & Removal"]

BIODIVERSITY_1 = ["Wildlife",
"Elimination of Species",
"Invasive Animals",
"Invasive Plants",
"Endangered Species",
"Climate Crime 'Ecocide'",
"Community Engagement",
"Ecosystems"]

THREATS_1 = ["Melting Glaciers", 
"Melting  Icecaps",
"Permafrost",
"Drought",
"Rising Sea Levels",
"Floods",
"Deforestation",
"Wild Fires",
"Rising Temperatures",
"Risk Management",
"Loss and Damage"]

THREATS_2 = ["FORESTS",
"DESERTS",
"MOUNTAINS",
"RIVERS", 
"OCEANS",
"ICE AND GLACIERS",
"MANGROVES"]

INDUSTRY_1 = ["Energy",
"Agriculture",
"Mining",
"Manufacturing",
"Logistics",
"Construction",
"Education",
"Training",
"Jobs",
"Youth Workforce"]

INDUSTRY_2 = ["Aquaponics",
"Hydroponics",
"Vertical Farming",
"Low Emission Farming",
"Climate Risk",
"Food Security"]

TRANSPORTATION_1 = ["Automobiles",
"Buses",
"Comercial Trucks",
"Aviation",
"Rail",
"Shipping"]

TRANSPORTATION_2 = ["Electric Powered",
"Solar Powered"]

SEEKING_SOLUTIONS_1 = ["Innovation",
"Geo-Engineering",
"Resilience",
"Green Cities",
"Sustainability",
"30/30 Target",
"Government Investment",
"Private Sector Investment",
"Conservation",
"Reforestation"]

SEEKING_SOLUTIONS_2 = ["Air Quality",
"Green Infrastructure",
"Water and Sanitation"]

INFLUENCERS_1 = ["UNITED NATIONS",
"FAMOUS NAMES",
"POLITICIANS",
"ACTIVISTS"
"DENIERS",
"DOOMERS",
"INDIGENOUS"]

INFLUENCERS_2 = ["Gutteres"]

SOCIAL_JUSTICE_1 = ["Legal",
"Health",
"Women & Climate Change",
"Diversity",
"Inclusion"]

SOCIAL_JUSTICE_2 = ["Nutrition",
"Adaptation"]

REGIONS_COUNTRIES = ["Disasters",
"Resilience",
"Impact",
"Community"]

REGIONS = ["NORTH AMERICA",
"SOUTH  & CENTRAL AMERICA",
"EUROPE & RUSSIA",
"AFRICA & MIDDLE EAST",
"ASIA",
"AUSTRALIA & PACIFIC ISLANDS",
"ARCTIC & ANTARCTICA",
"DEVELOPING NATIONS",
"EUROPEAN UNION",
"UNITED NATIONS",
"GLOBAL"]

COUNTRIES = ["Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bhutan",
"Bolivia",
"Bosnia and Herzegovina",
"Botswana",
"Brazil",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cabo Verde",
"Cambodia",
"Cameroon",
"Canada",
"Central African Republic",
"Chad",
"Chile",
"China",
"Colombia",
"Comoros",
"Congo",
"Costa Rica",
"Côte d’Ivoire",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"East Timor",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Eswatini",
"Ethiopia",
"Fiji",
"Finland",
"France",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Greece",
"Grenada",
"Guatemala",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Honduras",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"North Korea",
"South Korea",
"Kosovo",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Mauritania",
"Mauritius",
"Mexico",
"Micronesia",
"Moldova",
"Monaco",
"Mongolia",
"Montenegro",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"North Macedonia",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russia",
"Rwanda",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"Spain",
"Sri Lanka",
"Sudan",
"Sudan, South",
"Suriname",
"Sweden",
"Switzerland",
"Syria",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Togo",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"USA",
"US",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Vatican City",
"Venezuela",
"Vietnam",
"Yemen",
"Zambia",
"Zimbabwe"]